high_dollar_threshold: 300.00  # Transactions above this amount will be flagged for review

category_thresholds:
  shopping: 400.00
  subscriptions: 75.00
  utilities: 250.00

subscription:
  tracked_merchants:
    - spotify
    - amazon prime
    - peacock
    - xfinity
    - blizzard
    - la fitness

new_merchant:
  enabled: true
  ignore_merchants: []

reporting:
  tracked_expenses:
    - groceries
    - utilities
    - subscriptions
    - transportation
